[project]
name = "simulacao-de-fluidos-em-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "raylib==5.5.0.2",
]
